version: 0.0.1.{build}-test

shallow_clone: true

environment:
  LUAROCKS_VER: 2.2.2
  matrix:
  - LUA_VER: 5.1.5
  # - LUA_VER: 5.2.4  # Lua 5.2.4 with compatibility flags enabled (DLUA_COMPAT_ALL).
  - LUA_VER: 5.2.4  # Lua 5.2.4 with compatibility flags disabled.
    NOCOMPAT: true
  # - LUA_VER: 5.3.1  # Lua 5.3.1 with compatibility flags enabled (DLUA_COMPAT_5_2).
  - LUA_VER: 5.3.1  # Lua 5.3.1 with compatibility flags disabled.
    NOCOMPAT: true
  - LJ_VER: 2.0.4
  - LJ_VER: 2.1

platform:
  - x86
  - x64

configuration:
  - 2015

matrix:
  fast_finish: true

cache:
  - c:\lua -> .appveyor.yml
  - c:\external -> .appveyor.yml

install:
  - call .appveyor\set_compiler_env.bat
  - call .appveyor\install.bat
  - luarocks install busted

build_script:
  - busted -v
  - luarocks make rocks/lift-scm-0.rockspec
  - lift --help

test: off

