language: c

sudo: false

env:
  global:
    - LUAROCKS=2.2.2
  matrix:
    - LUA=lua5.2
    - LUA=lua5.3

branches:
  only:
    - master

before_install:
  - source .travis/setenv_lua.sh
  - luarocks install busted
  - luarocks install luacov
  - luarocks install luacov-coveralls

script:
  - busted -c

after_success:
  - luacov-coveralls -v

