language: c
sudo: false

addons:
  apt:
    sources:
      - kalakris-cmake
    packages:
      - cmake

env:
  global:
    - LUAROCKS=2.3.0
  matrix:
    - LUA=lua5.2
    - LUA=lua5.3
    - LUA=luajit2.0  # current head of 2.0 branch
    - LUA=luajit2.1  # current head of 2.1 branch

branches:
  only:
    - master

before_install:
  - source .ci/setenv_lua.sh

before_script:
  - luarocks install lpeg
  - luarocks install luv
  - luarocks install busted
  - luarocks install luacov
  - luarocks install luacov-coveralls

script:
  - LUA_INIT="require'luacov'" busted -v
  - luarocks make lift-scm-0.rockspec
  - cd $CI_HOME/examples/tasks && lift
  - cd $CI_HOME/examples/downloads && lift
  - cd $CI_HOME/examples/lua-logo && lift
  - cd $CI_HOME/examples/build-lua && lift
  - cd $CI_HOME/examples/count-cmd && lift count lua $CI_HOME
  - cd $CI_HOME

after_success:
  - luacov-coveralls -v

