language: c

sudo: false

env:
  global:
    - LUAROCKS=2.2.2
  matrix:
    - LUA=lua5.1
    - LUA=lua5.2
    - LUA=lua5.3
    - LUA=luajit     # latest stable version (2.0.3)
    - LUA=luajit2.0  # current head of 2.0 branch
    - LUA=luajit2.1  # current head of 2.1 branch

branches:
  only:
    - master

before_install:
  - source .travis/setenv_lua.sh

before_script:
  - luarocks install rocks/lift-scm-0.rockspec
  - luarocks install busted
  - luarocks install luacov
  - luarocks install luacov-coveralls

script:
  - lift --help
  - busted -c -v

after_success:
  - luacov-coveralls -v

