environment:
  LUAROCKS_VER: 2.3.0
  matrix:
  - LUA_VER: 5.2.4
    NOCOMPAT: true
  - LUA_VER: 5.3.2
    NOCOMPAT: true
  - LJ_VER: 2.0.4
  - LJ_VER: 2.1

platform:
  - x86
  - x64

configuration:
  - 2015

matrix:
  fast_finish: true

cache:
  - c:\lua -> .ci\appveyor.yml
  - c:\external -> .ci\appveyor.yml

# init:
#   - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
  - call .ci\set_compiler_env.bat
  - call .ci\install.bat

build_script:
  - luarocks install lpeg
  - luarocks install luv
  - luarocks install busted
  - busted -o tap -v
  - luarocks make
  - lift --help

after_build:
  - luarocks remove lift

test: off

# on_finish:
#   - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
