version: 0.1.{build}
skip_tags: true
shallow_clone: true

environment:
  LUAROCKS_VER: 2.2.2
  matrix:
  - LUA_VER: 5.1.5
  - LUA_VER: 5.3.1  # Lua 5.3.1 with compatibility flags disabled.
    NOCOMPAT: true
  - LJ_VER: 2.0.4
  - LJ_VER: 2.1

platform:
  - x86
  - x64

configuration:
  - 2015

matrix:
  fast_finish: true

cache:
  - c:\lua -> .ci\appveyor.yml
  - c:\external -> .ci\appveyor.yml

install:
  - call .ci\set_compiler_env.bat
  - call .ci\install.bat
  - set LIBUV_VERSION=1.7.5
  - appveyor DownloadFile https://github.com/libuv/libuv/archive/v%LIBUV_VERSION%.zip
  - 7z x v%LIBUV_VERSION%.zip & cd libuv-%LIBUV_VERSION% & vcbuild.bat %Platform% shared release
  - set LIBUV=C:\projects\lift\libuv-%LIBUV_VERSION%
  - set PATH=%PATH%;%LIBUV%

build_script:
  - luarocks install lluv UV_DIR=%LIBUV% UV_LIBDIR=%LIBUV%\Release
  - luarocks install busted
  - busted -v
  - luarocks make rocks/lift-scm-0.rockspec
  - lift --help

after_build:
  - luarocks remove lift

test: off

