version: 0.1.{build}
skip_tags: true
shallow_clone: true

environment:
  LUAROCKS_VER: 2.2.2
  matrix:
  - LUA_VER: 5.1.5
  - LUA_VER: 5.3.1  # Lua 5.3.1 with compatibility flags disabled.
    NOCOMPAT: true
  - LJ_VER: 2.0.4
  - LJ_VER: 2.1

platform:
  - x86
  - x64

configuration:
  - 2015

matrix:
  fast_finish: true

cache:
  - c:\lua -> .ci\appveyor.yml
  - c:\external -> .ci\appveyor.yml

install:
  - call .ci\set_compiler_env.bat
  - call .ci\install.bat
  - set ARCH=%platform%
  - set LIBUV_VERSION=1.7.5
  - appveyor DownloadFile http://dist.libuv.org/dist/v%LIBUV_VERSION%/libuv-%ARCH%-v%LIBUV_VERSION%.build7.exe
  - libuv-%ARCH%-v%LIBUV_VERSION%.build7.exe /NCRC /S
  - if "%ARCH%" EQU "x64" (set LIBUV=%ProgramFiles%\libuv) else (set LIBUV=%ProgramFiles(x86)%\libuv)
  - set PATH=%PATH%;%LIBUV%

build_script:
  - luarocks install lluv UV_DIR=%LIBUV%
  - luarocks install busted
  - busted -v --filter-out=scheduler
  - luarocks make rocks/lift-scm-0.rockspec
  - lift --help

after_build:
  - luarocks remove lift

test: off

