version: 0.1.{build}
skip_tags: true
shallow_clone: true

environment:
  LUAROCKS_VER: 2.2.2
  matrix:
  - LUA_VER: 5.1.5
  - LUA_VER: 5.3.1  # Lua 5.3.1 with compatibility flags disabled.
    NOCOMPAT: true
  - LJ_VER: 2.0.4
  - LJ_VER: 2.1

platform:
  - x86
  - x64

configuration:
  - 2015

matrix:
  fast_finish: true

cache:
  - c:\lua -> .ci\appveyor.yml
  - c:\external -> .ci\appveyor.yml

install:
  - call .ci\set_compiler_env.bat
  - call .ci\install.bat
  - appveyor DownloadFile https://github.com/libuv/libuv/archive/v1.7.5.zip
  - 7z x v1.7.5.zip & cd libuv-1.7.5 & vcbuild.bat %Platform% shared release
  - dir libuv-1.7.5\Release
  - dir libuv-1.7.5\Release\lib

build_script:
  - set PATH=%PATH%;C:\projects\lift\libuv-1.7.5\Release
  - luarocks install lluv UV_DIR=C:\projects\lift\libuv-1.7.5 UV_LIBDIR=C:\projects\lift\libuv-1.7.5\Release\lib
  - luarocks install busted
  - busted -v
  - luarocks make rocks/lift-scm-0.rockspec
  - lift --help

after_build:
  - luarocks remove lift

test: off

